### ISSUE TITLE
invalid continuation byte

### ISSUE THREAD

**Issue by nerdnils** [Moguri/panda3d-gltf#11]
$ gltf2bam sliderbar.glb sliderbar.bam
Traceback (most recent call last):
  File "/usr/bin/gltf2bam", line 11, in <module>
    load_entry_point('panda3d-gltf==0.1.0', 'console_scripts', 'gltf2bam')()
  File "/usr/lib/python3.7/site-packages/gltf/cli.py", line 44, in main
    gltf.converter.convert(args.src, args.dst, settings)
  File "/usr/lib/python3.7/site-packages/gltf/converter.py", line 1092, in convert
    gltf_data = json.load(gltf_file)
  File "/usr/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 12: invalid continuation byte

This really is only a box created in blender having a black principled bsdf shader. and a bit of bevel. Nothing special

**Comment by Moguri** [comment]
It looks like you are trying to convert a binary glTF file, which is not currently supported (see issue #4).
