### ISSUE TITLE
Tangent calculation raises ZeroDivisionError on some models

### ISSUE THREAD

**Issue by el-dee** [Moguri/panda3d-gltf#36]
Some models without tangent data cause the converter to crash due to division by zero.

<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/panda3d_gltf-0.3-py3.5.egg/gltf/converter.py", line 1310, in load_model
    convert(file_path, bamfilepath, gltf_settings)
  File "/usr/local/lib/python3.5/dist-packages/panda3d_gltf-0.3-py3.5.egg/gltf/converter.py", line 1288, in convert
    converter.update(gltf_data, writing_bam=True)
  File "/usr/local/lib/python3.5/dist-packages/panda3d_gltf-0.3-py3.5.egg/gltf/converter.py", line 150, in update
    self.load_mesh(meshid, gltf_mesh, gltf_data)
  File "/usr/local/lib/python3.5/dist-packages/panda3d_gltf-0.3-py3.5.egg/gltf/converter.py", line 1043, in load_mesh
    self.load_primitive(node, gltf_primitive, gltf_data)
  File "/usr/local/lib/python3.5/dist-packages/panda3d_gltf-0.3-py3.5.egg/gltf/converter.py", line 978, in load_primitive
    self.calculate_tangents(geom)
  File "/usr/local/lib/python3.5/dist-packages/panda3d_gltf-0.3-py3.5.egg/gltf/converter.py", line 1005, in calculate_tangents
    fconst = 1.0 / (duv1.x * duv2.y - duv2.x * duv1.y)
ZeroDivisionError: float division by zero
</pre>

Tested with the latest panda3d-gltf and Panda3d-1.10.5-dev92

One model causing the crash is the Hubble model available here : https://exoplanets.nasa.gov/resources/2214/hubble-space-telescope-3d-model/ but other models cause the same problem.

**Comment by rdb** [comment]
I'm not really sure why there's this constant term to begin with in the tangent/bitangent calculation.  The calculation doesn't produce unit vectors, so they have to be normalised anyway.

**Comment by rdb** [comment]
For the record, glTF mandates use of the [MikkTSpace](https://archive.blender.org/wiki/index.php/Dev:Shading/Tangent_Space_Normal_Maps/) algorithm for tangent generation to ensure better interoperability:
> **Implementation note:** When tangents are not specified, client implementations should calculate tangents using default MikkTSpace algorithms.  For best results, the mesh triangles should also be processed using default MikkTSpace algorithms.

It may be worth filing an issue upstream to get MikkTSpace implemented in the Panda3D Geom class.

**Comment by Moguri** [comment]
I believe this issue was resolved with #38, so I am closing this issue. Please feel free to reopen it if you are still running into problems.
