### ISSUE TITLE
Animation export ends with ZeroDivisionError

### ISSUE THREAD

**Issue by kergalym** [Moguri/panda3d-gltf#72]
Hi, 
Animation export ends with

Blender quit
Traceback (most recent call last):
  File "/home/galym/Korlan/venv3.7/lib/python3.7/site-packages/blend2bam/cli.py", line 89, in convert
    tmp2dst.convert_single(tmpfile.name, dst)
  File "/home/galym/Korlan/venv3.7/lib/python3.7/site-packages/blend2bam/gltf2bam/__init__.py", line 20, in convert_single
    gltf.converter.convert(src, dst, settings)
  File "/home/galym/Korlan/venv3.7/lib/python3.7/site-packages/gltf/converter.py", line 1613, in convert
    converter.update(gltf_data, writing_bam=True)
  File "/home/galym/Korlan/venv3.7/lib/python3.7/site-packages/gltf/converter.py", line 356, in update
    add_node(scene_root, gltf_scene, nodeid, {}, {})
  File "/home/galym/Korlan/venv3.7/lib/python3.7/site-packages/gltf/converter.py", line 206, in add_node
    self.build_character(panda_node, nodeid, jvtmap, cvsmap, gltf_data)
  File "/home/galym/Korlan/venv3.7/lib/python3.7/site-packages/gltf/converter.py", line 1006, in build_character
    fps = num_frames / time_data[-1]
ZeroDivisionError: float division by zero

Failed to convert all files

It happens when animations starts from 0. Same for Blender 2.8 glTF exporter

**Comment by Moguri** [comment]
I suspect this is happening on actions that *end* on 0, which is likely a single frame action at time 0. @rdb Do you have a recommendation for fps on a single-frame animations? 30? I am pretty sure that the fps value will not matter, but I may be missing some corner cases.

**Comment by rdb** [comment]
I reckon it doesn't matter.  Might as well just set it to the historical Panda default, 24.  I don't know what happens if you set it to 0 in Panda.

**Comment by Moguri** [comment]
@kergalym Can you please see if c4f4e3c solves the problem for you?
